/** Random pool for bump-version.js — card-game puns, no duplicates in BUILD_CODENAMES. */
module.exports = [
  "Ace Up the Sleeve",
  "Asshole Ascendant",
  "Bluff Buffet",
  "Bottom Deck Energy",
  "Card Shark Week",
  "Cut the Deck",
  "Dealer's Remorse",
  "Double Down Darling",
  "Empty Hand Heroics",
  "Felt Table Fever",
  "Flush With Hubris",
  "Fold Em And Hold Em",
  "Four Of A Kind Mind",
  "Grand Slam Gamble",
  "High Card Hijinks",
  "Joker's Wild Ride",
  "King Me Maybe",
  "Last Card Standing",
  "Misdeal Mayhem",
  "No Pass Zone",
  "Off-Suit Outburst",
  "Pass Parade",
  "Pile On Patrol",
  "President's Day Off",
  "Quad Squad Goals",
  "Rank And File",
  "Run It Back",
  "Shuffle Or Scramble",
  "Table Stakes Tantrum",
  "Ten High Drama",
  "Trick Question",
  "Trump Card Tantrum",
  "Underhand Overhand",
  "Wild Draw Four Energy",
  "Your Turn, Apparently",
];
