import fs from "node:fs";
import path from "node:path";

// Canonical wallpaper data imports a binary asset for the app bundle. The
// generator needs only its preset values, so ignore that asset in Node.
require.extensions[".webp"] = () => {};

const { getCardFaceColors } = require("../src/utils/cardFaceTheme") as typeof import("../src/utils/cardFaceTheme");
const { FELT_PRESETS, DEFAULT_FELT_COLOR } = require("../src/services/wallpaper") as typeof import("../src/services/wallpaper");
const { deriveFeltPalette, buildThemeBundle } = require("../src/styles/feltPalette") as typeof import("../src/styles/feltPalette");

const outputPath = path.resolve(__dirname, "../site-root/site-theme.generated.js");

const presets = FELT_PRESETS.map((preset) => {
  const palette = deriveFeltPalette(preset.hex);
  return {
    name: preset.name,
    hex: preset.hex,
    surface: palette.feltSurface,
    accent: palette.complementBright,
    accentDim: palette.complementDim,
    lightAccent: palette.complementDim,
    surfaces: {
      dark: previewSurfaceTokens(buildThemeBundle(preset.hex, "dark", "auto").colors),
      light: previewSurfaceTokens(buildThemeBundle(preset.hex, "light", "auto").colors),
    },
  };
});

function previewSurfaceTokens(colors: ReturnType<typeof buildThemeBundle>["colors"]) {
  return {
    glass: `rgba(${colors.frostRgb}, ${colors.blur.panel.webOpacity})`,
    border: colors.panelBorder,
    text: colors.textPrimary,
    control: colors.btnSecondaryBg,
  };
}

const theme = {
  defaultFelt: DEFAULT_FELT_COLOR,
  presets,
  cards: {
    light: getCardFaceColors(false),
    dark: getCardFaceColors(true),
  },
};

const output = `/* Generated by scripts/generate-site-theme.ts. Do not edit manually. */\nwindow.PS_AND_AS_SITE_THEME = ${JSON.stringify(theme, null, 2)};\n`;
fs.writeFileSync(outputPath, output, "utf8");
console.log(`Generated ${presets.length} felt presets at ${path.relative(process.cwd(), outputPath)}`);
